apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: layer7-gateway-dashboard
    files:
      - "./layer7-gateway-dashboard.json"

